language: python

cache: pip

python:
  - '2.7'
  - '3.6'

matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

install:
  - pip install -U pip setuptools
  - pip install -U pytest flake8-tuple flake8-quotes flake8-comprehensions flake8-commas flake8-builtins

script:
  - python setup.py test
  - flake8 disco/
